"""Add rule_string to Rule model

Revision ID: 3a56d2b6c1ae
Revises: 
Create Date: 2024-10-21 00:26:53.879263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a56d2b6c1ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('rule_string', sa.Text(), nullable=False, server_default=''))
    # Remove server_default after the column is added
    op.alter_column('rules', 'rule_string', server_default=None)
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_column('rule_string')

    # ### end Alembic commands ###
